Document: upgradevision11
Title: Debian upgradevision11 Manual
Author: <insert document author here>
Abstract: This manual describes what upgradevision11 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/upgradevision11/upgradevision11.sgml.gz

Format: postscript
Files: /usr/share/doc/upgradevision11/upgradevision11.ps.gz

Format: text
Files: /usr/share/doc/upgradevision11/upgradevision11.text.gz

Format: HTML
Index: /usr/share/doc/upgradevision11/html/index.html
Files: /usr/share/doc/upgradevision11/html/*.html
